const express = require('express')
const customersRouter = require('./src/routes/customers')
const customersAddressRouter = require('./src/routes/customersAddress')
const authenticationRouter = require('./src/routes/authentication')
const venueRouter = require('./src/routes/venue')
const eventsRouter = require('./src/routes/event')
const paymentRouter = require('./src/routes/payment')
const ticketsRouter = require('./src/routes/tickets')
const eventDateRouter = require('./src/routes/eventDate')
const ticketBatchRouter = require('./src/routes/ticketBatches')
const transactionRouter = require('./src/routes/transactions')
const cartRouter = require('./src/routes/carts')
const mediaRouter = require('./src/routes/media')

module.exports = function (app) {
  app.use('/customers', customersRouter)
  app.use('/authentication', authenticationRouter)
  app.use('/customersAddress', customersAddressRouter)
  app.use('/venues', venueRouter)
  app.use('/events', eventsRouter)
  app.use('/payments', paymentRouter)
  app.use('/tickets', ticketsRouter)
  app.use('/eventsDates', eventDateRouter)
  app.use('/ticketBatches', ticketBatchRouter)
  app.use('/transactions', transactionRouter)
  app.use('/carts', cartRouter)
  app.use('/media', mediaRouter)
}